// This file is generated by Slice Machine. Update with care!

import Banner from './Banner';
import Content from './Content';
import TitleBlock from './TitleBlock';

export {
	Banner,
	Content,
	TitleBlock,
};

export const components = {
	banner: Banner,
	content: Content,
	title_block: TitleBlock,
};
